# Generated by Django 6.0.6 on 2026-06-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('status', models.BooleanField()),
                ('image', models.ImageField(upload_to='product/')),
                ('category', models.ManyToManyField(related_name='products', to='product.category')),
            ],
        ),
    ]
