# Generated by Django 6.0.6 on 2026-06-08 11:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_category_image_alter_category_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='آدرس ایمیل')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام کامل')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', verbose_name='شماره تلفن')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/', verbose_name='عکس پروفایل')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('product', models.ManyToManyField(blank=True, to='product.product', verbose_name='محصولات مورد علاقه')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
